# MYSQL test
# CREATE TABLE user (
#     question1 int,
#     question2 int,
#     question3 int,
#     question4 int,
#     question5 int,
#     question6 int,
#     question7 int,
#     question8 int,
#     question9 int,
#     question10 int,
#     question11 int,
#     question12 int,
#     question13 int,
#     question14 int,
#     question15 int,
#     question16 int,
#     question16 int,
#     question17 int,
#     question18 int,
#     question19 int,
#     question20 int,
#     question21 int,
#     question22 int,
#     question23 int,
#     question24 int,
#     question25 int,
#     question26 int,
#     question27 int,
#     question28 int,
#     question29 int,
#     question30 int,
#     question31 int,
#     question32 int,
#     question33 int,
#     question34 int,
#     question35 int,
#     question36 int,
#     question37 int,
#     question38 int,
#     question39 int,
#     question40 int,
#     question41 int,
#     question42 int,
#     question43 int,
#     question44 int,
#     question45 int,
#     question46 int,
#     question47 int,
#     question48 int,
#     question49 int,
#     question50 int,
#     question51 int,
#     question52 int,
#     question53 int,
#     question54 int,
#     question55 int,
#     question56 int,
#     question57 int,
#     question58 int,
#     question59 int,
#     question60 int,
    
    
    
    
# );
